pipeline:

  test:
    image: node:6
    commands:
      - npm i
      - npm test
    when:
      event: [push, pull_request, tag]

  publish_to_artifactory:
    image: node:6
    secrets:
      - npm_config_auth
    commands:
      - npm adduser
      - npm publish
    when:
      event: [tag]

matrix:
  NPM_CONFIG_USERNAME:
    - regt-build-bot