pipeline:

  test:
    image: node:10
    secrets:
      - npm_auth_token
    commands:
      - npm i
      - npm test
    when:
      event: [push, pull_request, tag]

  publish_to_artifactory:
    image: node:10
    secrets:
      - npm_auth_token
    commands:
      - npm publish
    when:
      event: [tag]

matrix:
  NPM_AUTH_USERNAME:
    - regt-build-bot